# No home-manager module yet, so the config file is generated by hand. Per
# cluster overrides go in sofka/clusters/<name>/config.toml if ever needed.
{ sofka, pkgs, ... }:
{
  home.packages = [ sofka ];

  xdg.configFile."sofka/config.toml".source = (pkgs.formats.toml { }).generate "sofka-config" {
    # Same shorthands as k9s.nix.
    aliases = {
      dp = "deployments";
      sec = "secrets";
      jo = "jobs";
      cr = "clusterroles";
      crb = "clusterrolebindings";
      ro = "roles";
      rb = "rolebindings";
      np = "networkpolicies";
    };
  };
}
