{ ... }:
let

  # Breeze dark color scheme

  # Primary color
  primary = "${blue}";
  r_primary = "${r_blue}";
  h_primary = "#${primary}";
  f_primary = "#${primary}FF";
  q_primary = "'#${primary}'";

  solid_alpha = "1.00";
  half_alpha = "0.50";

  # Colors without hastag
  background = "202326";
  background_alt = "292C30";
  foreground = "FCFCFC";
  foreground_muted = "A1A9B1";
  black = "272C31";
  red = "DA4453";
  green = "27AE60";
  yellow = "F67400";
  blue = "3DAEE9";
  purple = "9B59B6";
  cyan = "1ABC9C";
  white = "FCFCFC";
  bright_black = "4F5B64";
  bright_red = "E06C75";
  bright_green = "2ECC71";
  bright_yellow = "FDBC4B";
  bright_blue = "6CBFF6";
  bright_purple = "B48EAD";
  bright_cyan = "4FD1C5";
  bright_white = "FFFFFF";
  highlight = "3DAEE9";
  positive = "27AE60";
  warning = "F67400";
  error = "DA4453";
  link = "1D99F3";

  # Value of rgb (must match the hex above)
  v_background = "32, 35, 38";
  v_background_alt = "41, 44, 48";
  v_foreground = "252, 252, 252";
  v_foreground_muted = "161, 169, 177";
  v_black = "39, 44, 49";
  v_red = "218, 68, 83";
  v_green = "39, 174, 96";
  v_yellow = "246, 116, 0";
  v_blue = "61, 174, 233";
  v_purple = "155, 89, 182";
  v_cyan = "26, 188, 156";
  v_white = "252, 252, 252";
  v_bright_black = "79, 91, 100";
  v_bright_red = "224, 108, 117";
  v_bright_green = "46, 204, 113";
  v_bright_yellow = "253, 188, 75";
  v_bright_blue = "108, 191, 246";
  v_bright_purple = "180, 142, 173";
  v_bright_cyan = "79, 209, 197";
  v_bright_white = "255, 255, 255";
  v_highlight = "61, 174, 233";
  v_positive = "39, 174, 96";
  v_warning = "246, 116, 0";
  v_error = "218, 68, 83";
  v_link = "29, 153, 243";

  # Colors with hastag
  h_background = "#${background}";
  h_background_alt = "#${background_alt}";
  h_foreground = "#${foreground}";
  h_foreground_muted = "#${foreground_muted}";
  h_black = "#${black}";
  h_red = "#${red}";
  h_green = "#${green}";
  h_yellow = "#${yellow}";
  h_blue = "#${blue}";
  h_purple = "#${purple}";
  h_cyan = "#${cyan}";
  h_white = "#${white}";
  h_bright_black = "#${bright_black}";
  h_bright_red = "#${bright_red}";
  h_bright_green = "#${bright_green}";
  h_bright_yellow = "#${bright_yellow}";
  h_bright_blue = "#${bright_blue}";
  h_bright_purple = "#${bright_purple}";
  h_bright_cyan = "#${bright_cyan}";
  h_bright_white = "#${bright_white}";
  h_highlight = "#${highlight}";
  h_positive = "#${positive}";
  h_warning = "#${warning}";
  h_error = "#${error}";
  h_link = "#${link}";

  # Colors with hastag & alpha
  f_background = "#${background}FF";
  f_background_alt = "#${background_alt}FF";
  f_foreground = "#${foreground}FF";
  f_foreground_muted = "#${foreground_muted}FF";
  f_black = "#${black}FF";
  f_red = "#${red}FF";
  f_green = "#${green}FF";
  f_yellow = "#${yellow}FF";
  f_blue = "#${blue}FF";
  f_purple = "#${purple}FF";
  f_cyan = "#${cyan}FF";
  f_white = "#${white}FF";
  f_bright_black = "#${bright_black}FF";
  f_bright_red = "#${bright_red}FF";
  f_bright_green = "#${bright_green}FF";
  f_bright_yellow = "#${bright_yellow}FF";
  f_bright_blue = "#${bright_blue}FF";
  f_bright_purple = "#${bright_purple}FF";
  f_bright_cyan = "#${bright_cyan}FF";
  f_bright_white = "#${bright_white}FF";
  f_highlight = "#${highlight}FF";
  f_positive = "#${positive}FF";
  f_warning = "#${warning}FF";
  f_error = "#${error}FF";
  f_link = "#${link}FF";

  # Colors with hastag & double-single quote
  q_background = "'#${background}'";
  q_background_alt = "'#${background_alt}'";
  q_foreground = "'#${foreground}'";
  q_foreground_muted = "'#${foreground_muted}'";
  q_black = "'#${black}'";
  q_red = "'#${red}'";
  q_green = "'#${green}'";
  q_yellow = "'#${yellow}'";
  q_blue = "'#${blue}'";
  q_purple = "'#${purple}'";
  q_cyan = "'#${cyan}'";
  q_white = "'#${white}'";
  q_bright_black = "'#${bright_black}'";
  q_bright_red = "'#${bright_red}'";
  q_bright_green = "'#${bright_green}'";
  q_bright_yellow = "'#${bright_yellow}'";
  q_bright_blue = "'#${bright_blue}'";
  q_bright_purple = "'#${bright_purple}'";
  q_bright_cyan = "'#${bright_cyan}'";
  q_bright_white = "'#${bright_white}'";
  q_highlight = "'#${highlight}'";
  q_positive = "'#${positive}'";
  q_warning = "'#${warning}'";
  q_error = "'#${error}'";
  q_link = "'#${link}'";

  # Colors with full alpha value rgba
  r_background = "rgba(${v_background}, ${solid_alpha})";
  r_background_alt = "rgba(${v_background_alt}, ${solid_alpha})";
  r_foreground = "rgba(${v_foreground}, ${solid_alpha})";
  r_foreground_muted = "rgba(${v_foreground_muted}, ${solid_alpha})";
  r_black = "rgba(${v_black}, ${solid_alpha})";
  r_red = "rgba(${v_red}, ${solid_alpha})";
  r_green = "rgba(${v_green}, ${solid_alpha})";
  r_yellow = "rgba(${v_yellow}, ${solid_alpha})";
  r_blue = "rgba(${v_blue}, ${solid_alpha})";
  r_purple = "rgba(${v_purple}, ${solid_alpha})";
  r_cyan = "rgba(${v_cyan}, ${solid_alpha})";
  r_white = "rgba(${v_white}, ${solid_alpha})";
  r_bright_black = "rgba(${v_bright_black}, ${solid_alpha})";
  r_bright_red = "rgba(${v_bright_red}, ${solid_alpha})";
  r_bright_green = "rgba(${v_bright_green}, ${solid_alpha})";
  r_bright_yellow = "rgba(${v_bright_yellow}, ${solid_alpha})";
  r_bright_blue = "rgba(${v_bright_blue}, ${solid_alpha})";
  r_bright_purple = "rgba(${v_bright_purple}, ${solid_alpha})";
  r_bright_cyan = "rgba(${v_bright_cyan}, ${solid_alpha})";
  r_bright_white = "rgba(${v_bright_white}, ${solid_alpha})";
  r_highlight = "rgba(${v_highlight}, ${solid_alpha})";
  r_positive = "rgba(${v_positive}, ${solid_alpha})";
  r_warning = "rgba(${v_warning}, ${solid_alpha})";
  r_error = "rgba(${v_error}, ${solid_alpha})";
  r_link = "rgba(${v_link}, ${solid_alpha})";

  # Colors with half alpha value rgba
  rh_background = "rgba(${v_background}, ${half_alpha})";
  rh_background_alt = "rgba(${v_background_alt}, ${half_alpha})";
  rh_foreground = "rgba(${v_foreground}, ${half_alpha})";
  rh_foreground_muted = "rgba(${v_foreground_muted}, ${half_alpha})";
  rh_black = "rgba(${v_black}, ${half_alpha})";
  rh_red = "rgba(${v_red}, ${half_alpha})";
  rh_green = "rgba(${v_green}, ${half_alpha})";
  rh_yellow = "rgba(${v_yellow}, ${half_alpha})";
  rh_blue = "rgba(${v_blue}, ${half_alpha})";
  rh_purple = "rgba(${v_purple}, ${half_alpha})";
  rh_cyan = "rgba(${v_cyan}, ${half_alpha})";
  rh_white = "rgba(${v_white}, ${half_alpha})";
  rh_bright_black = "rgba(${v_bright_black}, ${half_alpha})";
  rh_bright_red = "rgba(${v_bright_red}, ${half_alpha})";
  rh_bright_green = "rgba(${v_bright_green}, ${half_alpha})";
  rh_bright_yellow = "rgba(${v_bright_yellow}, ${half_alpha})";
  rh_bright_blue = "rgba(${v_bright_blue}, ${half_alpha})";
  rh_bright_purple = "rgba(${v_bright_purple}, ${half_alpha})";
  rh_bright_cyan = "rgba(${v_bright_cyan}, ${half_alpha})";
  rh_bright_white = "rgba(${v_bright_white}, ${half_alpha})";
  rh_highlight = "rgba(${v_highlight}, ${half_alpha})";
  rh_positive = "rgba(${v_positive}, ${half_alpha})";
  rh_warning = "rgba(${v_warning}, ${half_alpha})";
  rh_error = "rgba(${v_error}, ${half_alpha})";
  rh_link = "rgba(${v_link}, ${half_alpha})";

in
{

  inherit primary;
  inherit h_primary;
  inherit f_primary;
  inherit q_primary;
  inherit r_primary;

  inherit solid_alpha;
  inherit half_alpha;

  inherit background;
  inherit background_alt;
  inherit foreground;
  inherit foreground_muted;
  inherit black;
  inherit red;
  inherit green;
  inherit yellow;
  inherit blue;
  inherit purple;
  inherit cyan;
  inherit white;
  inherit bright_black;
  inherit bright_red;
  inherit bright_green;
  inherit bright_yellow;
  inherit bright_blue;
  inherit bright_purple;
  inherit bright_cyan;
  inherit bright_white;
  inherit highlight;
  inherit positive;
  inherit warning;
  inherit error;
  inherit link;

  inherit h_background;
  inherit h_background_alt;
  inherit h_foreground;
  inherit h_foreground_muted;
  inherit h_black;
  inherit h_red;
  inherit h_green;
  inherit h_yellow;
  inherit h_blue;
  inherit h_purple;
  inherit h_cyan;
  inherit h_white;
  inherit h_bright_black;
  inherit h_bright_red;
  inherit h_bright_green;
  inherit h_bright_yellow;
  inherit h_bright_blue;
  inherit h_bright_purple;
  inherit h_bright_cyan;
  inherit h_bright_white;
  inherit h_highlight;
  inherit h_positive;
  inherit h_warning;
  inherit h_error;
  inherit h_link;

  inherit f_background;
  inherit f_background_alt;
  inherit f_foreground;
  inherit f_foreground_muted;
  inherit f_black;
  inherit f_red;
  inherit f_green;
  inherit f_yellow;
  inherit f_blue;
  inherit f_purple;
  inherit f_cyan;
  inherit f_white;
  inherit f_bright_black;
  inherit f_bright_red;
  inherit f_bright_green;
  inherit f_bright_yellow;
  inherit f_bright_blue;
  inherit f_bright_purple;
  inherit f_bright_cyan;
  inherit f_bright_white;
  inherit f_highlight;
  inherit f_positive;
  inherit f_warning;
  inherit f_error;
  inherit f_link;

  inherit q_background;
  inherit q_background_alt;
  inherit q_foreground;
  inherit q_foreground_muted;
  inherit q_black;
  inherit q_red;
  inherit q_green;
  inherit q_yellow;
  inherit q_blue;
  inherit q_purple;
  inherit q_cyan;
  inherit q_white;
  inherit q_bright_black;
  inherit q_bright_red;
  inherit q_bright_green;
  inherit q_bright_yellow;
  inherit q_bright_blue;
  inherit q_bright_purple;
  inherit q_bright_cyan;
  inherit q_bright_white;
  inherit q_highlight;
  inherit q_positive;
  inherit q_warning;
  inherit q_error;
  inherit q_link;

  inherit r_background;
  inherit r_background_alt;
  inherit r_foreground;
  inherit r_foreground_muted;
  inherit r_black;
  inherit r_red;
  inherit r_green;
  inherit r_yellow;
  inherit r_blue;
  inherit r_purple;
  inherit r_cyan;
  inherit r_white;
  inherit r_bright_black;
  inherit r_bright_red;
  inherit r_bright_green;
  inherit r_bright_yellow;
  inherit r_bright_blue;
  inherit r_bright_purple;
  inherit r_bright_cyan;
  inherit r_bright_white;
  inherit r_highlight;
  inherit r_positive;
  inherit r_warning;
  inherit r_error;
  inherit r_link;

  inherit rh_background;
  inherit rh_background_alt;
  inherit rh_foreground;
  inherit rh_foreground_muted;
  inherit rh_black;
  inherit rh_red;
  inherit rh_green;
  inherit rh_yellow;
  inherit rh_blue;
  inherit rh_purple;
  inherit rh_cyan;
  inherit rh_white;
  inherit rh_bright_black;
  inherit rh_bright_red;
  inherit rh_bright_green;
  inherit rh_bright_yellow;
  inherit rh_bright_blue;
  inherit rh_bright_purple;
  inherit rh_bright_cyan;
  inherit rh_bright_white;
  inherit rh_highlight;
  inherit rh_positive;
  inherit rh_warning;
  inherit rh_error;
  inherit rh_link;

}
